### ISSUE TITLE
🗂 Epic: People Tab

### ISSUE THREAD

**Issue by christianivanis** [Chatmosphere/chatmosphere-app#132]
- [ ] see total number of participants
- [ ] participants can browse and find other participants in a form of list
- [ ] know that mine and others connections are stable

Vision
- [ ] Search for participants
- [ ] Submenu with more actions
- [ ] Animated mic input to see who is talking
- [ ] Dynamic section of participants that share to everyone on top of the list
- [ ] Video Avatars of participants that share to everyone

Explore the [design here](https://design.penpot.app/#/view/041b11e0-4935-11ec-b61d-6194167bb409?page-id=157c45d0-492b-11ec-a354-794827c67032&section=interactions&index=0&share-id=7d3c0f50-8a69-11ec-952b-9eafb5cb1e0f) in a clickable Prototype. Start at the clickable tab in the lower right corner.

<img width="259" alt="Bildschirmfoto 2022-02-14 um 14 38 50" src="https://user-images.githubusercontent.com/91052318/153874645-ddd1157e-ea8d-40e9-a25a-5d934f2d0fcc.png">
