### ISSUE TITLE
🗂  Epic: Be seen and heard by everyone without being intrusive (Stage)

### ISSUE THREAD

**Issue by dkgrieshammer** [Chatmosphere/chatmosphere-app#98]
### Description
To prevent crampoing of many folks around users that have an interesting conversation going (e.g. a talk or some kind of presentation) we want to be able to listen to them without the need to fit all into their audio radius; 

### Todos / Missing Features:
- [ ]  needs a way to be muted
- [ ] needs a way to hide it
- [ ] should be scalable
- [ ] should be repositionable

**Comment by dkgrieshammer** [comment]
We currently can go to stage (stage branch - preview on app.dev.chatmosphere.cc)
- needs a way to be muted 
- needs a way to hide it
- should be scalable
- should be repositionable

**Comment by EnidKapelsen** [comment]
Specification for "not being intrusive": 

- [ ] I can mute a person on the stage
- [ ] A visual representation is still shown to indicate, that there is activity on the stage
- [ ] If no one is on the stage, the visual representation disappears
- [ ] If a new person enters the stage, the last state is active (muted for example)
